### PR TITLE
Pipe android sdk tarball to tar

### PR DESCRIPTION
**Pull request by ismail-s**
No need to create a temporary file

### CODE REVIEW

**Comment by hpssjellis** [comment]
This repository is the practice repo for a docker file that runs the android sdk online on Cloud9, (still in Beta version). Can you change your PR to comment out not delete my lines of code since I may need them later. Nice Pipe by the way.

**Comment by hpssjellis** [comment]
wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O - | tar -xvf -

is the final dash needed?

**Comment by ismail-s** [comment]
with the f flag, I think so. I am saying that the file that tar should read in from is stdin.

**Comment by ismail-s** [comment]
@hpssjellis Also, as a suggestion, https://circleci.com/docs/android/ suggests that for installing sdk packages, you can use `echo y | android update sdk blah` to auto-accept the license agreement.

**Pull request closed without merging**
